In [1]:
import sys
import glob
from netCDF4 import Dataset
import pandas as pd
import numpy as np

# netcdf file read


Create a netCDF4.Dataset object
--------------------------------
* <span style="color:#2D3748; background-color:#fff5b1;">f</span> is a Dataset object, representing an open netCDF file.
* printing the object gives you summary information, similar to ncdump -h.

In [2]:
file = r"D:\Study\20220317_python\20211002_03\GK2_GOCI2_L1B_20211002_031500_RLA_S0009_HG_rhowSpec.nc"
print(file)

D:\Study\20220317_python\20211002_03\GK2_GOCI2_L1B_20211002_031500_RLA_S0009_HG_rhowSpec.nc


In [3]:
f = Dataset(file)
print(f)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    product_name: GK2_GOCI2_L1B_20211002_031500_RLA_S0009_HG_rhowSpec.nc
    projection_type: GEOS
    sub_longitude: 2.2375121010567303
    nominal_satellite_height: 42164000.0
    earth_radius: 6378137.0
    earth_equatorial_radius: 6378137.0
    perspective_point_height: 35785863.0
    image_upperleft_x: -0.0313145
    image_upperleft_y: 0.0897435
    image_lowerright_x: -0.011861499999999997
    image_lowerright_y: 0.0702905
    image_upperleft_latitude: 0.5505231616896651
    image_upperleft_longitude: 2.0237435851380536
    image_lowerright_latitude: 0.4155291226008265
    image_lowerright_longitude: 2.163611005042577
    nband: 12
    wavelength: [381.  412.5 443.8 490.7 510.5 555.2 620.  660.1 680.1 709.1 745.5 864.1]
    wavelength_unit: nm
    dimensions(sizes): dim_image_x(2780), dim_image_y(2780), bands(12)
    variables(dimensions): 
    groups: geophysical_data


# Access a netCDF group/variable
* **variable** objects stored by name in variables dict.
* print the variable yields summary info (including all the attributes).
* no actual data read yet (just have a reference to the variable object with metadata).

In [4]:
print(f.variables.keys()) # get all variable names
# temp = f.variables['temperature']  # temperature variable
# print(temp) 


dict_keys([])


In [5]:
print(f.groups.keys())
geo = f.groups['geophysical_data']
print(geo)
print(geo.variables.keys())
data = geo.variables['data'] #data variable
print(data)

dict_keys(['geophysical_data'])
<class 'netCDF4._netCDF4.Group'>
group /geophysical_data:
    dimensions(sizes): 
    variables(dimensions): float32 data(bands, dim_image_y, dim_image_x)
    groups: 
dict_keys(['data'])
<class 'netCDF4._netCDF4.Variable'>
float32 data(bands, dim_image_y, dim_image_x)
path = /geophysical_data
unlimited dimensions: 
current shape = (12, 2780, 2780)
filling on, default _FillValue of 9.969209968386869e+36 used


List the Dimensions
-------------------

* All variables in a netCDF file have an associated shape, specified by a list of dimensions.
* Let's list all the dimensions in this netCDF file.
* ~~Note that the MT dimension is special (unlimited), which means it can be appended to.~~

Each variable has a dimensions and a shape attribute.

In [10]:
for d in f.dimensions.items():
    print(d)

for d in data.dimensions :
    print(d)

('dim_image_x', <class 'netCDF4._netCDF4.Dimension'>: name = 'dim_image_x', size = 2780)
('dim_image_y', <class 'netCDF4._netCDF4.Dimension'>: name = 'dim_image_y', size = 2780)
('bands', <class 'netCDF4._netCDF4.Dimension'>: name = 'bands', size = 12)
bands
dim_image_y
dim_image_x


In [11]:
data.shape

(12, 2780, 2780)

Get value from NetCDF Variable

In [20]:
banddata = data[:]
print('shape of banddata: %s' % repr(banddata.shape))
print(banddata)

shape of banddata: (12, 2780, 2780)
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  