In [1]:
import sys
import glob
from netCDF4 import Dataset
import pandas as pd
import numpy as np

# netcdf file read


Create a netCDF4.Dataset object
--------------------------------
* <span style="color:#2D3748; background-color:#fff5b1;">f</span> is a Dataset object, representing an open netCDF file.
* printing the object gives you summary information, similar to ncdump -h.

In [2]:
# file = r"D:\Study\20220317_python\20211002_03\GK2_GOCI2_L1B_20211002_031500_RLA_S0009_HG_rhowSpec.nc"
file = r"D:\Study\20220208_g2\GK2_GOCI2_L1B_20220108_021530_LA_S007.nc"
print(file)

D:\Study\20220208_g2\GK2_GOCI2_L1B_20220108_021530_LA_S007.nc


In [3]:
f = Dataset(file)
print(f)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    title: GK2B GOCI-II Level-1B Radiances
    summary: GK2B GOCI-II Level-1B Radiances
    id: 1.2.7_20210721/GK2_GOCI2_L1B_20220108_021530_LA_S007.nc
    naming_authority: kr.ac.kiost.kosc
    product_name: GK2_GOCI2_L1B_20220108_021530_LA_S007.nc
    product_version: 1.0.0_20191030
    history: BAND_CNT = 12
BAND1_THRESHOLD = 100.546
BAND2_THRESHOLD = 146.1
BAND3_THRESHOLD = 134.852
BAND4_THRESHOLD = 127.781
BAND5_THRESHOLD = 118.605
BAND6_THRESHOLD = 109.935
BAND7_THRESHOLD = 92.956
BAND8_THRESHOLD = 84.836
BAND9_THRESHOLD = 81.822
BAND10_THRESHOLD = 77.244
BAND11_THRESHOLD = 65.778
BAND12_THRESHOLD = 42.903
HG = /input/GK2_GOCI2_L1B_20220108_021500_RLA_S0007_HG.nc
LG = /input/GK2_GOCI2_L1B_20220108_021500_RLA_S0007_LG.nc
STATIC = /main_storage_temp/G2GS/STATIC
OUTPUT = /output/GK2_GOCI2_L1B_20220108_021530_LA_S007.nc

    creator_name: KIOST/KOSC
    creator_email: kosc@kiost.ac.kr
    creator_ur

# Access a netCDF group/variable
* **variable** objects stored by name in variables dict.
* print the variable yields summary info (including all the attributes).
* no actual data read yet (just have a reference to the variable object with metadata).

In [4]:
print(f.variables.keys()) # get all variable names
# temp = f.variables['temperature']  # temperature variable
# print(temp) 


dict_keys([])


In [6]:
print(f.groups.keys())
geo = f.groups['geophysical_data']
print(geo)
print(geo.variables.keys())
# data = geo.variables['data'] #data variable
data = geo.variables['L_TOA_745']
print(data)

dict_keys(['geophysical_data', 'navigation_data'])
<class 'netCDF4._netCDF4.Group'>
group /geophysical_data:
    dimensions(sizes): 
    variables(dimensions): uint32 L_TOA_380(number_of_columns, number_of_lines), uint32 L_TOA_412(number_of_columns, number_of_lines), uint32 L_TOA_443(number_of_columns, number_of_lines), uint32 L_TOA_490(number_of_columns, number_of_lines), uint32 L_TOA_510(number_of_columns, number_of_lines), uint32 L_TOA_555(number_of_columns, number_of_lines), uint32 L_TOA_620(number_of_columns, number_of_lines), uint32 L_TOA_660(number_of_columns, number_of_lines), uint32 L_TOA_680(number_of_columns, number_of_lines), uint32 L_TOA_709(number_of_columns, number_of_lines), uint32 L_TOA_745(number_of_columns, number_of_lines), uint32 L_TOA_865(number_of_columns, number_of_lines)
    groups: 
dict_keys(['L_TOA_380', 'L_TOA_412', 'L_TOA_443', 'L_TOA_490', 'L_TOA_510', 'L_TOA_555', 'L_TOA_620', 'L_TOA_660', 'L_TOA_680', 'L_TOA_709', 'L_TOA_745', 'L_TOA_865'])
<class 'netC

List the Dimensions
-------------------

* All variables in a netCDF file have an associated shape, specified by a list of dimensions.
* Let's list all the dimensions in this netCDF file.
* ~~Note that the MT dimension is special (unlimited), which means it can be appended to.~~

Each variable has a dimensions and a shape attribute.

In [7]:
for d in f.dimensions.items():
    print(d)

for d in data.dimensions :
    print(d)

('number_of_columns', <class 'netCDF4._netCDF4.Dimension'>: name = 'number_of_columns', size = 2780)
('number_of_lines', <class 'netCDF4._netCDF4.Dimension'>: name = 'number_of_lines', size = 2780)
number_of_columns
number_of_lines


In [8]:
data.shape

(2780, 2780)

Get value from NetCDF Variable

In [9]:
banddata = data[:]
print('shape of banddata: %s' % repr(banddata.shape))
print(banddata)

shape of banddata: (2780, 2780)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Calc lat/lon from attribute
===========================

* get attribute from nc file


In [11]:
from pyproj import Proj
import math

sl = f.sub_longitude
sl2 = sl* 180 / math.pi
sl3 =str(sl2).strip()
print(sl, sl2, sl3)

nsh = f.nominal_satellite_height
er = f.earth_radius
# h1 = nsh - er
h1 = f.perspective_point_height
h2 = str(h1).strip()
print(h1, h2)
p = Proj(proj='geos', h=h2, lon_0 = sl3, sweep='x')



128.2 7345.318758724311 7345.318758724311
35786000.0 35786000.0
